#!/bin/bash
MASTER_IP=$1

while :
do

  HASH_OLD=""
  if [[ -f /var/hadoop/provsioning/conf.md5 ]]; then
    HASH_OLD=`cat /var/hadoop/provsioning/conf.md5`
  fi

  HASH_NEW=`curl http://${MASTER_IP}:7777/conf-hash/`

  if [[ "${HASH_OLD}" != "${HASH_NEW}" ]]; then
    echo "${HASH_NEW}" > /var/hadoop/provsioning/conf.md5
    wget -O /var/hadoop/provsioning/conf.tgz http://${MASTER_IP}:7777/conf-data/
    if [[ -f /var/hadoop/provsioning/conf.tgz ]]; then
      tar -xzvf /var/hadoop/provsioning/conf.tgz
      mv -f etc/hadoop/* /etc/hadoop/
    fi
  fi

  sleep 10

done

